{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "My (partly unfounded) theory is that we should refactor `ApplyOOMScoreAdjContainer` out of `runContainerInPod` because if the container exited real quick it won't have an entry in `/proc/pid/cgroup` (https://github.com/kubernetes/kubernetes/blob/d3b869ae14db522e5fca91a295b8bc870713013f/pkg/kubelet/dockertools/manager.go#L1537), and we confuse this for an error in running the container.\n\nThis is based off the following debugging session:\nhttp://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/14712/ \n`pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp` has `restart=Never` and it seems to exit, and we don't report it as failed/succeeded. \n1. Started container:\n   I0120 22:10:22.967700    3461 server.go:569] Event(api.ObjectReference{Kind:\"Pod\", \n   Namespace:\"e2e-tests-emptydir-fbgqp\", Name:\"**pod-995d097b-bfc2-11e5-9ce3-42010af01555**\", \n   UID:\"995d410d-bfc2-11e5-9d46-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"8929\", \n   FieldPath:\"spec.containers{test-container}\"}): type: 'Normal' reason: 'Started' Started container with \n   docker id fab06c2e3ee6\n2. Failed to set oom score:\n   **E0120 22:10:23.007292**    3461 manager.go:1890] Error running pod \"pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp(995d410d-bfc2-11e5-9d46-42010af00002)\" **container \"test-container\": open /proc/17193/cgroup: no such file or directory**\n3. FailedSync event:\n   I0120 22:10:23.070581    3461 server.go:569] Event(api.ObjectReference{Kind:\"Pod\", \n   Namespace:\"e2e-tests-emptydir-fbgqp\", Name:\"pod-995d097b-bfc2-11e5-9ce3-42010af01555\", \n   UID:\"995d410d-bfc2-11e5-9d46-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"8929\", \n   FieldPath:\"\"}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: not all containers have \n   started: 0 != 1\n4. However if you track the next 2 container inspect results: \n   - I0120 22:10:23.053457    3461 manager.go:340] Container inspect result: \n     {ID:**fab06c2e3ee6eaff383bbb3d9f77ded5d692e20e7c77d849bdfdfdc6fe475baf** Created:2016-01-20 \n     22:10:22.821645807 +0000 UTC Path:/mt Args:[--fs_type=/test-volume --new_file_0644=/test-\n     volume/test-file --file_perm=/test-volume/test-file] Config:0xc208408fc0 State:{Running:true \n     Paused:false Restarting:false OOMKilled:false **Pid:17193 ExitCode:0 Error: StartedAt:2016-01-20 \n     22:10:22.967310973 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC}** \n     Image\n   - I0120 22:10:23.328738    3461 manager.go:340] Container inspect result: \n     {ID:**fab06c2e3ee6eaff383bbb3d9f77ded5d692e20e7c77d849bdfdfdc6fe475baf** Created:2016-01-20\n     22:10:22.821645807 +0000 UTC Path:/mt Args:[--fs_type=/test-volume --new_file_0644=/test-\n     volume/test-file --file_perm=/test-volume/test-file] Config:0xc208748380 State:{Running:false \n     Paused:false Restarting:false OOMKilled:false Pid:0 **ExitCode:0 Error: StartedAt:2016-01-20\n     22:10:22.967310973 +0000 UTC FinishedAt:2016-01-20 22:10:23.06969655 +0000 \n     UTC}** ResolvConfPath:\n5. And we sent the Running/Ready update but no status update after that:\n   I0120 22:10:23.080449    3461 manager.go:371] Status for pod \"pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp(995d410d-bfc2-11e5-9d46-42010af00002)\" updated successfully: {status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x2bba980}} LastTransitionTime:{Time:{sec:63588924623 nsec:0 loc:0x2bba980}} Reason: Message:}] Message: Reason: HostIP:10.240.0.5 PodIP:10.248.84.65 \n\n@kubernetes/goog-node thoughts?\n",
  "closed_at": "2016-02-08T23:25:45Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 4,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/20117/comments",
  "created_at": "2016-01-25T23:15:17Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/20117/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/20117",
  "id": 128670602,
  "labels": [
    {
      "color": "c7def8",
      "default": false,
      "description": "Categorizes issue or PR as related to cleaning up code, process, or technical debt.",
      "id": 122775691,
      "name": "kind/cleanup",
      "node_id": "MDU6TGFiZWwxMjI3NzU2OTE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/cleanup"
    },
    {
      "color": "fbca04",
      "default": false,
      "description": "Higher priority than priority/awaiting-more-evidence.",
      "id": 114528273,
      "name": "priority/backlog",
      "node_id": "MDU6TGFiZWwxMTQ1MjgyNzM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/backlog"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/20117/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxMjg2NzA2MDI=",
  "number": 20117,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Kubelet fails to distinguish failure in running container from a quickly exiting container",
  "updated_at": "2016-02-08T23:25:45Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/20117",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/10927820?v=4",
    "events_url": "https://api.github.com/users/bprashanth/events{/privacy}",
    "followers_url": "https://api.github.com/users/bprashanth/followers",
    "following_url": "https://api.github.com/users/bprashanth/following{/other_user}",
    "gists_url": "https://api.github.com/users/bprashanth/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/bprashanth",
    "id": 10927820,
    "login": "bprashanth",
    "node_id": "MDQ6VXNlcjEwOTI3ODIw",
    "organizations_url": "https://api.github.com/users/bprashanth/orgs",
    "received_events_url": "https://api.github.com/users/bprashanth/received_events",
    "repos_url": "https://api.github.com/users/bprashanth/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/bprashanth/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bprashanth/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/bprashanth"
  }
}