{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "/kind bug\r\n\r\n**What happened**:\r\n\r\nI incorrectly specified a pod toleration with `effect=CriticalAddonsOnly` instead of `key=CriticalAddonsOnly`, and the resulting validation error was nonsensical.\r\n\r\nThe full incorrect set of tolerations is:\r\n\r\n```yaml\r\n- effect: CriticalAddonsOnly\r\n  operator: Exists\r\n- effect: NoExecute\r\n  operator: Exists\r\n```\r\n\r\nWhen I submit this pod to Kubernetes I get the following validation error:\r\n\r\n```\r\nDaemonSet.apps \"calico-node\" is invalid: spec.template.spec.tolerations[0].effect: Unsupported value: \"NoExecute\": supported values: \"NoSchedule\", \"PreferNoSchedule\", \"NoExecute\"\r\n```\r\n\r\nNote that it correctly identifies the first toleration as incorrect, but says that `NoExecute` is both invalid and one of the supported values, even though `NoExecute` appears nowhere in that toleration.\r\n\r\nThis appears to happen only when there is a `NoExecute` toleration following the malformed toleration. If I remove the second toleration from this pod, the validation fails with the correct error:\r\n\r\n```\r\nDaemonSet.apps \"calico-node\" is invalid: spec.template.spec.tolerations[0].effect: Unsupported value: \"CriticalAddonsOnly\": supported values: \"NoSchedule\", \"PreferNoSchedule\", \"NoExecute\"\r\n```\r\n\r\nThis smells a lot like accidentally using an iteration value in a for loop without copying it first, such that just traversing the `NoExecute` toleration ends up corrupting the error for the first toleration.\r\n\r\n**What you expected to happen**:\r\n\r\nThe validation error should make sense.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\nSubmit a pod to Kubernetes with the above tolerations set.\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): 1.10.2\r\n- Cloud provider or hardware configuration: Bare metal\r\n- OS (e.g. from /etc/os-release): Debian Testing\r\n- Kernel (e.g. `uname -a`): 4.16.5\r\n- Install tools: kubeadm",
  "closed_at": "2018-05-31T00:34:15Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 3,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/64301/comments",
  "created_at": "2018-05-25T06:14:33Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/64301/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/64301",
  "id": 326394168,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG API Machinery.",
      "id": 173493835,
      "name": "sig/api-machinery",
      "node_id": "MDU6TGFiZWwxNzM0OTM4MzU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/api-machinery"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/64301/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzMjYzOTQxNjg=",
  "number": 64301,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Malformed toleration produces unhelpful validation error",
  "updated_at": "2018-05-31T00:34:15Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/64301",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1918?v=4",
    "events_url": "https://api.github.com/users/danderson/events{/privacy}",
    "followers_url": "https://api.github.com/users/danderson/followers",
    "following_url": "https://api.github.com/users/danderson/following{/other_user}",
    "gists_url": "https://api.github.com/users/danderson/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/danderson",
    "id": 1918,
    "login": "danderson",
    "node_id": "MDQ6VXNlcjE5MTg=",
    "organizations_url": "https://api.github.com/users/danderson/orgs",
    "received_events_url": "https://api.github.com/users/danderson/received_events",
    "repos_url": "https://api.github.com/users/danderson/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/danderson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/danderson/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/danderson"
  }
}