{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "CONTRIBUTOR",
  "body": "\r\n**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n\r\n/kind bug\r\n\r\n**What happened**:\r\n\r\nWhen using the legacy docker container runtime and when a container has `terminationMessagePolicy=FallbackToLogsOnError` and when docker is configured with a log driver other than `json-log` (such as `journald`), the kublet still tries to fetch the last few lines of the container logs from the json log file. When it tries, it gets a message like this:\r\n\r\n```\r\nError on reading termination message from logs: failed to open log file \"/var/log/pods/f36cd8db-9984-11e7-9d0f-54e1ad486deb/busybox_0.log\": open /var/log/pods/f36cd8db-9984-11e7-9d0f-54e1ad486deb/busybox_0.log: no such file or directory\r\n```\r\n\r\n**What you expected to happen**:\r\n\r\nThe kubelet should not try to get the container's log from the json log file (since it's not there) but should instead ask docker for the logs.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n1. Configure `dockerd` to use the `journald` log driver. Add `--log-driver=journald` to its command line.\r\n2. Create a pod with a container that has `terminationMessagePolicy` set to `FallbackToLogsOnError`. For example, put the following into `busybox-pod.yaml`:\r\n```\r\n---\r\napiVersion: v1\r\nkind: Pod\r\nmetadata:\r\n  name: busybox-pod\r\nspec:\r\n  containers:\r\n  - image: gcr.io/google_containers/busybox\r\n    name: busybox\r\n    terminationMessagePolicy: FallbackToLogsOnError\r\n    command: [\"/bin/sh\"]\r\n    args: [\"-c\", \"echo Last line of container log; exit 1\"]\r\n  restartPolicy: Never\r\n```\r\nthen run\r\n```\r\nkubectl create -f ~/busybox-pod.yaml\r\n```\r\n3. Wait for the pod to exit with an error\r\n4. Look at the termination message:\r\n```\r\nkubectl get pod -o go-template=\"{{index .status.containerStatuses 0 \"state\" \"terminated\" \"message\"}}' busybox-pod\r\n```\r\nIf you have reproduced the problem, you'll see something like the above error message. If it's working, you'll see\r\n```\r\nLast line of container log\r\n```\r\n\r\n**Anything else we need to know?**:\r\nThis is related to #42195 from a few months ago.",
  "closed_at": "2017-10-17T20:18:15Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 1,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52502/comments",
  "created_at": "2017-09-14T20:12:35Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52502/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/52502",
  "id": 257842399,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52502/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUyNTc4NDIzOTk=",
  "number": 52502,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Error when using journald log driver and FallbackToLogsOnError",
  "updated_at": "2017-10-17T20:18:15Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52502",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/329907?v=4",
    "events_url": "https://api.github.com/users/joelsmith/events{/privacy}",
    "followers_url": "https://api.github.com/users/joelsmith/followers",
    "following_url": "https://api.github.com/users/joelsmith/following{/other_user}",
    "gists_url": "https://api.github.com/users/joelsmith/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/joelsmith",
    "id": 329907,
    "login": "joelsmith",
    "node_id": "MDQ6VXNlcjMyOTkwNw==",
    "organizations_url": "https://api.github.com/users/joelsmith/orgs",
    "received_events_url": "https://api.github.com/users/joelsmith/received_events",
    "repos_url": "https://api.github.com/users/joelsmith/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/joelsmith/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/joelsmith/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/joelsmith"
  }
}