{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "**Kubernetes version** (use `kubectl version`):\n\nClient Version: version.Info{Major:\"1\", Minor:\"4+\", GitVersion:\"v1.4.0-beta.11\", GitCommit:\"4b28af1232cc52da453eb4ebe3dc001314a1f99b\", GitTreeState:\"clean\", BuildDate:\"2016-09-23T22:53:01Z\", GoVersion:\"go1.6.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\nServer Version: version.Info{Major:\"1\", Minor:\"4\", GitVersion:\"v1.4.0\", GitCommit:\"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b\", GitTreeState:\"clean\", BuildDate:\"2016-09-26T18:10:32Z\", GoVersion:\"go1.6.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\n\n**Environment**:\nAWS - CentOS 7.2 x86_64 with cloud-init (HVM) (ami-666a7507)\n- **OS** (e.g. from /etc/os-release):\n  NAME=\"CentOS Linux\"\n  VERSION=\"7 (Core)\"\n  ID=\"centos\"\n  ID_LIKE=\"rhel fedora\"\n  VERSION_ID=\"7\"\n  PRETTY_NAME=\"CentOS Linux 7 (Core)\"\n  ANSI_COLOR=\"0;31\"\n  CPE_NAME=\"cpe:/o:centos:centos:7\"\n  HOME_URL=\"https://www.centos.org/\"\n  BUG_REPORT_URL=\"https://bugs.centos.org/\"\n\nCENTOS_MANTISBT_PROJECT=\"CentOS-7\"\nCENTOS_MANTISBT_PROJECT_VERSION=\"7\"\nREDHAT_SUPPORT_PRODUCT=\"centos\"\nREDHAT_SUPPORT_PRODUCT_VERSION=\"7\"\n\nLinux ip-172-31-35-103 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux\n- **Install tools**:\n- **Others**:\n\n**What happened**:\nwhen selinux is enabled   i was getting following error on discovery container\n\n``` sh\n[root@ip-172-31-35-103 ec2-user]# docker logs 905535c9a143\n2016/09/27 07:50:38 Unable to open root CA certificate (\"/tmp/secret/ca.pem\" [open /tmp/secret/ca.pem: permission denied])\n```\n\n**What you expected to happen**:\ni expected node to be able to join master, but  nothing was running on 9898 port of master i.e. discovery due the error mentioned above\n\n**How to reproduce it** (as minimally and precisely as possible):\nuse the api which i gave you and do normal kubeadm init \n\n**Anything else do we need to know**:\nThis issue got fixed with setenforce 0\n",
  "closed_at": "2016-09-27T17:06:48Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 8,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/33541/comments",
  "created_at": "2016-09-27T08:10:17Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/33541/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/33541",
  "id": 179424280,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": null,
      "id": 136601536,
      "name": "area/apiserver",
      "node_id": "MDU6TGFiZWwxMzY2MDE1MzY=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/apiserver"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/33541/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxNzk0MjQyODA=",
  "number": 33541,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "kubeadm join issue on CentOS 7.2 (when selinux is enabled)",
  "updated_at": "2016-09-27T17:06:48Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/33541",
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/1439169?v=4",
    "events_url": "https://api.github.com/users/debianmaster/events{/privacy}",
    "followers_url": "https://api.github.com/users/debianmaster/followers",
    "following_url": "https://api.github.com/users/debianmaster/following{/other_user}",
    "gists_url": "https://api.github.com/users/debianmaster/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/debianmaster",
    "id": 1439169,
    "login": "debianmaster",
    "node_id": "MDQ6VXNlcjE0MzkxNjk=",
    "organizations_url": "https://api.github.com/users/debianmaster/orgs",
    "received_events_url": "https://api.github.com/users/debianmaster/received_events",
    "repos_url": "https://api.github.com/users/debianmaster/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/debianmaster/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/debianmaster/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/debianmaster"
  }
}