{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!\r\n\r\nIf the matter is security related, please disclose it privately via https://kubernetes.io/security/\r\n-->\r\n\r\n\r\n**What happened**:\r\nI have an running ipv6-only cluster using IPVS.  The pod to pod and pod to service communication is working fine. But I am not able to access the pod externally using nodeport. \r\n\r\n sudo kubectl get svc\r\nNAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                         AGE\r\nelasticsearch   NodePort    fd20::91c1   <none>        9200:32140/TCP,9300:30866/TCP   15s\r\nkubernetes      ClusterIP   fd20::1      <none>        443/TCP                         4m33s\r\n\r\n sudo kubectl get pods -o wide\r\nNAME                             READY   STATUS    RESTARTS   AGE   IP           NODE    NOMINATED NODE   READINESS GATES\r\nelasticsearch-669dc996cd-bsrcg   1/1     Running   0          19m   fd20::7043   demo1   <none>           <none>\r\n\r\n**What you expected to happen:**\r\n\r\nI expected to have an ipvs rule related to node port. But no entry in IPVS. \r\n\r\nIP Virtual Server version 1.2.1 (size=4096)\r\nProt LocalAddress:Port Scheduler Flags\r\n  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn\r\nTCP  [fd20::1]:443 rr\r\n  -> [2001:db8:0:f101::2]:6443    Masq    1      5          0\r\nTCP  [fd20::a]:53 rr\r\n  -> [fd20::7041]:53              Masq    1      0          0\r\n  -> [fd20::7042]:53              Masq    1      0          0\r\nTCP  [fd20::a]:9153 rr\r\n  -> [fd20::7041]:9153            Masq    1      0          0\r\n  -> [fd20::7042]:9153            Masq    1      0          0\r\nTCP  [fd20::91c1]:9200 rr\r\n  -> [fd20::7043]:9200            Masq    1      0          0\r\nTCP  [fd20::91c1]:9300 rr\r\n  -> [fd20::7043]:9300            Masq    1      0          0\r\nUDP  [fd20::a]:53 rr\r\n  -> [fd20::7041]:53              Masq    1      0          0\r\n  -> [fd20::7042]:53              Masq    1      0          0\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): Kubernetes v1.17.2\r\n- Network Plugin/Version : Calico Version  -  v 3.10.2\r\n- OS (e.g: `cat /etc/os-release`):  Ubuntu 16.04.5 LTS\r\n- Kernel (e.g. `uname -a`): Linux demo1 4.4.0-131-generic #157-Ubuntu  x86_64 GNU/Linux\r\n- Tools used:  kubeadm \r\n\r\n**How to reproduce it (as minimally and precisely as possible):**\r\n1. install latest kubernetes (v.1.17.2) version \r\n2. create a pod as type nodeport.\r\n\r\n**Anything else we need to know?**:\r\nI could see lots of error messages in kube-proxy \r\n\r\nE0128 08:08:55.468535       1 proxier.go:1976] Failed to add destination: [fd20::7043]:9200, error: file exists\r\nE0128 08:08:55.468740       1 graceful_termination.go:144] Delete rs \"[fd20::91c1]:9200/TCP/253.32.0.0:9200\" err: Delete destination \"253.32.0.0:9200\" err: no such file or directory\r\nE0128 08:08:55.468785       1 proxier.go:2006] Failed to delete destination: [fd20::91c1]:9200/TCP/253.32.0.0:9200, error: no such file or directory\r\nE0128 08:08:55.469064       1 proxier.go:1976] Failed to add destination: [fd20::7043]:9300, error: file exists\r\nE0128 08:08:55.469177       1 graceful_termination.go:144] Delete rs \"[fd20::91c1]:9300/TCP/253.32.0.0:9300\" err: Delete destination \"253.32.0.0:9300\" err: no such file or directory\r\nE0128 08:08:55.469230       1 proxier.go:2006] Failed to delete destination: [fd20::91c1]:9300/TCP/253.32.0.0:9300, error: no such file or directory\r\nE0128 08:08:55.469531       1 proxier.go:1976] Failed to add destination: [fd20::7041]:53, error: file exists\r\nE0128 08:08:55.469600       1 proxier.go:1976] Failed to add destination: [fd20::7042]:53, error: file exists\r\nE0128 08:08:55.469713       1 graceful_termination.go:144] Delete rs \"[fd20::a]:53/TCP/253.32.0.0:53\" err: Delete destination \"253.32.0.0:53\" err: no such file or directory\r\nE0128 08:08:55.469781       1 proxier.go:2006] Failed to delete destination: [fd20::a]:53/TCP/253.32.0.0:53, error: no such file or directory.\r\n\r\n\r\n\r\n\r\n",
  "closed_at": "2020-02-07T01:46:01Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 10,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/87604/comments",
  "created_at": "2020-01-28T09:32:38Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/87604/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/87604",
  "id": 556084934,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Network.",
      "id": 116712108,
      "name": "sig/network",
      "node_id": "MDU6TGFiZWwxMTY3MTIxMDg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/network"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/87604/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU1NTYwODQ5MzQ=",
  "number": 87604,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Nodeport issues with ipv6-only Cluster",
  "updated_at": "2020-02-07T01:46:01Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/87604",
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/60239552?v=4",
    "events_url": "https://api.github.com/users/etavene/events{/privacy}",
    "followers_url": "https://api.github.com/users/etavene/followers",
    "following_url": "https://api.github.com/users/etavene/following{/other_user}",
    "gists_url": "https://api.github.com/users/etavene/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/etavene",
    "id": 60239552,
    "login": "etavene",
    "node_id": "MDQ6VXNlcjYwMjM5NTUy",
    "organizations_url": "https://api.github.com/users/etavene/orgs",
    "received_events_url": "https://api.github.com/users/etavene/received_events",
    "repos_url": "https://api.github.com/users/etavene/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/etavene/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/etavene/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/etavene"
  }
}