{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!\r\n\r\nIf the matter is security related, please disclose it privately via https://kubernetes.io/security/\r\n-->\r\n\r\n\r\n**What happened**:\r\nEnvironment: On GCE with the win-bridge cni plugin\r\n\r\nOn a node when creating a pod for the first time, running podsandbox would fail with the error message below. \"failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392)\"\r\n\r\n```\r\nEvents:\r\n  Type     Reason                  Age                From                                              Message\r\n  ----     ------                  ----               ----                                              -------\r\n  Warning  FailedCreatePodSandBox  15s                kubelet, e2e-test-yjhong-windows-node-group-rdt6  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container \"5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106\" network for pod \"shetland\": NetworkPlugin cni failed to set up pod \"shetland_default\" network: error while ProvisionEndpoint(5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge,359CAE70-8CA4-4143-A42B-42644CF04022,5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106): failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392), failed to clean up sandbox container \"5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106\" network for pod \"shetland\": NetworkPlugin cni failed to teardown pod \"shetland_default\" network: failed to find HNSEndpoint 5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge: Endpoint 5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge not found]\r\n  Normal   SandboxChanged          12s (x2 over 14s)  kubelet, e2e-test-yjhong-windows-node-group-rdt6  Pod sandbox changed, it will be killed and re-created.\r\n\r\n```\r\nSubsequent retry would succeed, and launching other pods afterwards would also, generally, be fine. \r\n\r\nI've found https://github.com/Microsoft/SDN/issues/298, but in that issue, the creation failed permanently.\r\n\r\n\r\n**What you expected to happen**:\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): master (1.14, da5fd93e93f4)\r\n- Cloud provider or hardware configuration: GCE\r\n- OS (e.g: `cat /etc/os-release`): Windows 1809\r\n- Kernel (e.g. `uname -a`):\r\n- Install tools:\r\n- Others:\r\n\r\n/cc @pjh @kubernetes/sig-windows-bugs ",
  "closed_at": "2019-03-02T04:35:04Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 5,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/74766/comments",
  "created_at": "2019-03-01T01:31:05Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/74766/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/74766",
  "id": 415900043,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Windows.",
      "id": 422106010,
      "name": "sig/windows",
      "node_id": "MDU6TGFiZWw0MjIxMDYwMTA=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/windows"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/74766/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0MTU5MDAwNDM=",
  "number": 74766,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Creating windows pods flaky due to HNS error \"failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392)\"",
  "updated_at": "2019-03-02T04:35:04Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/74766",
  "user": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/10524058?v=4",
    "events_url": "https://api.github.com/users/yujuhong/events{/privacy}",
    "followers_url": "https://api.github.com/users/yujuhong/followers",
    "following_url": "https://api.github.com/users/yujuhong/following{/other_user}",
    "gists_url": "https://api.github.com/users/yujuhong/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/yujuhong",
    "id": 10524058,
    "login": "yujuhong",
    "node_id": "MDQ6VXNlcjEwNTI0MDU4",
    "organizations_url": "https://api.github.com/users/yujuhong/orgs",
    "received_events_url": "https://api.github.com/users/yujuhong/received_events",
    "repos_url": "https://api.github.com/users/yujuhong/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/yujuhong/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yujuhong/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/yujuhong"
  }
}