{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n\r\n/kind bug\r\n\r\n**What happened**:\r\n\r\ne2e test \"[sig-network] Network [It] should set TCP CLOSE_WAIT timeout\" requires the test target OS supports /proc/net/nf_conntrack, but Ubuntu 16.04 doesn't support it.\r\nThen the test fails today like the following:\r\n```\r\nSTEP: Checking /proc/net/nf_conntrack for the timeout\r\nSep 17 23:29:38.946: INFO: Getting external IP address for k8s-master\r\nSep 17 23:29:38.946: INFO: SSH \"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\" on k8s-master(192.168.1.108:22)\r\nSep 17 23:29:39.258: INFO: ssh ubuntu@192.168.1.108:22: command:   sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\r\nSep 17 23:29:39.259: INFO: ssh ubuntu@192.168.1.108:22: stdout:    \"\"\r\nSep 17 23:29:39.259: INFO: ssh ubuntu@192.168.1.108:22: stderr:    \"cat: /proc/net/nf_conntrack: No such file or directory\\n\"\r\nSep 17 23:29:39.260: INFO: ssh ubuntu@192.168.1.108:22: exit code: 1\r\nSep 17 23:29:39.260: INFO: Unexpected error occurred: failed running \"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\": <nil> (exit code 1)\r\n[AfterEach] [sig-network] Network\r\n  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:142\r\n...\r\n~ Failure [18.318 seconds]\r\n[sig-network] Network\r\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:22\r\n  should set TCP CLOSE_WAIT timeout [It]\r\n  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/kube_proxy.go:50\r\n\r\n  Expected error:\r\n      <*errors.errorString | 0xc420b0e430>: {\r\n          s: \"failed running \\\"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\\\": <nil> (exit code 1)\",\r\n      }\r\n      failed running \"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\": <nil> (exit code 1)\r\n  not to have occurred\r\n\r\n  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/kube_proxy.go:178\r\n------------------------------\r\n```\r\n\r\n**What you expected to happen**:\r\n\r\nThe test succeeded or was skipped.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\nJust kick\r\n```\r\n$ go run hack/e2e.go --provider=skeleton -- test --test_args=\"--ginkgo.focus=should\\sset\\sTCP\\sCLOSE_WAIT\\stimeout\"\r\n```\r\n**Anything else we need to know?**:\r\n\r\nThe existence of /proc/net/nf_conntrack depends on the Linux kernel config CONFIG_NF_CONNTRACK_PROCFS, but that is disabled on Ubuntu 16.04.\r\nIn addition, the test is skipped if the node number is less than 2.\r\nSo I guess that is one of reasons this issue was not present until today.\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): v1.11.3\r\n- Cloud provider or hardware configuration: OpenStack\r\n- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS\r\n- Kernel (e.g. `uname -a`): 4.4.0-134-generic\r\n- Install tools: kubeadm\r\n- Others:\r\n",
  "closed_at": "2018-11-09T18:20:02Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 3,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/69588/comments",
  "created_at": "2018-10-09T19:39:27Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/69588/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/69588",
  "id": 368365191,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Network.",
      "id": 116712108,
      "name": "sig/network",
      "node_id": "MDU6TGFiZWwxMTY3MTIxMDg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/network"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/69588/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzNjgzNjUxOTE=",
  "number": 69588,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "/proc/net/nf_conntrack doesn't exist on Ubuntu 16.04",
  "updated_at": "2020-05-02T08:18:35Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/69588",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1287154?v=4",
    "events_url": "https://api.github.com/users/oomichi/events{/privacy}",
    "followers_url": "https://api.github.com/users/oomichi/followers",
    "following_url": "https://api.github.com/users/oomichi/following{/other_user}",
    "gists_url": "https://api.github.com/users/oomichi/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/oomichi",
    "id": 1287154,
    "login": "oomichi",
    "node_id": "MDQ6VXNlcjEyODcxNTQ=",
    "organizations_url": "https://api.github.com/users/oomichi/orgs",
    "received_events_url": "https://api.github.com/users/oomichi/received_events",
    "repos_url": "https://api.github.com/users/oomichi/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/oomichi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oomichi/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/oomichi"
  }
}