{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "/kind bug\r\n\r\n**What happened**:\r\nWith a 1 master+3 worker node cluster (1.9.2) and 3 pods with PVs, the controller-manager fails to detach these PVs from the nodes after draining and upgrading to 1.9.5. This causes the pod to hang in the \"ContainerCreating\" state.\r\n```\r\n  Warning  FailedMount            58s (x12 over 26m)  kubelet, 84495dab-9d26-49e1-9a5a-b34d36ce12be  Unable to mount volumes for pod \"sample-statefulset-1_default(eb468d21-3ddb-11e8-89ea-0050568d2fa5)\": timeout expired waiting for volumes to attach/mount for pod \"default\"/\"sample-statefulset-1\". list of unattached/unmounted volumes=[www]\r\n  Warning  FailedMount            56s (x17 over 26m)  attachdetach-controller                        AttachVolume.Attach failed for volume \"pvc-92b732f7-3dd3-11e8-b882-0050568d2fa5\" : Failed to add disk 'scsi1:0'.\r\n```\r\n\r\n**What you expected to happen**:\r\nThe disk should be detached from the nodes and the pods should be restored to the running state. \r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n1. Create a cluster with k8s 1.9.2\r\n1. Deploy a workload with persistent volumes, replicated across the cluster\r\n1. Upgrade the cluster to k8s 1.9.5, by first upgrading the master node, then by upgrading the workers in the following order:\r\n        - Drain the node (`kubectl drain <node>`)\r\n        - upgrade node to k8s 1.9.5\r\n        - uncordon the node\r\n\r\n**Anything else we need to know?**:\r\nThis seems to be occuring because of the changes to the vsphere cloudprovider in 1.9.4, which causes the master node in 1.9.5 to be unable to recognize and identify the 1.9.2 nodes, resulting in the following logs:\r\n\r\n```\r\nI0323 13:21:54.954344    6021 reconciler.go:231] attacherDetacher.DetachVolume started for volume \"nil\" (UniqueName: \"kubernetes.io/vsphere-volume/[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk\") on node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" \r\nI0323 13:21:54.959794    6021 operation_generator.go:1165] Verified volume is safe to detach for volume \"nil\" (UniqueName: \"kubernetes.io/vsphere-volume/[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk\") on node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" \r\nE0323 13:21:54.968942    6021 datacenter.go:78] Unable to find VM by UUID. VM UUID: 21a524c0-7812-4f2f-a886-1e93b80e9881\r\nE0323 13:21:54.968960    6021 nodemanager.go:275] Error \"No VM found\" node info for node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" not found\r\nE0323 13:21:54.968970    6021 vsphere.go:475] Cannot find node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" in cache. Node not found!!!\r\nE0323 13:21:54.968980    6021 attacher.go:260] Error checking if volume (\"[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk\") is already attached to current node (\"21a524c0-7812-4f2f-a886-1e93b80e9881\"). Will continue and try detach anyway. err=No VM found\r\nE0323 13:21:54.976573    6021 datacenter.go:78] Unable to find VM by UUID. VM UUID: 21a524c0-7812-4f2f-a886-1e93b80e9881\r\nE0323 13:21:54.976589    6021 nodemanager.go:275] Error \"No VM found\" node info for node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" not found\r\nE0323 13:21:54.976597    6021 vsphere.go:475] Cannot find node \"21a524c0-7812-4f2f-a886-1e93b80e9881\" in cache. Node not found!!!\r\nE0323 13:21:54.976607    6021 attacher.go:274] Error detaching volume \"[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk\": No VM found\r\n```\r\n\r\nRestarting the kube-controller-manager also causes it to hang in a state where it continuously attempts to try and mount the pvc, flooding the logs in kubelet and also in vcenter:\r\n```\r\nI0406 03:22:49.954013   22290 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume \"pvc-e517c716-3946-11e8-9efa-005056b9781f\" (UniqueName: \"kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk\") pod \"sample-storage-95d4b8495-mkx9w\" (UID: \"b95d83dd-3949-11e8-b2d4-005056b9781f\") \r\n\r\nE0406 03:23:15.765047   22290 nestedpendingoperations.go:263] Operation for \"\\\"kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk\\\"\" failed. No retries permitted until 2018-04-06 03:23:16.264995909 +0000 UTC m=+98.801076882 (durationBeforeRetry 500ms). Error: \"Volume not attached according to node status for volume \\\"pvc-e517c716-3946-11e8-9efa-005056b9781f\\\" (UniqueName: \\\"kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk\\\") pod \\\"sample-storage-95d4b8495-mkx9w\\\" (UID: \\\"b95d83dd-3949-11e8-b2d4-005056b9781f\\\") \"\r\n\r\n```\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): 1.9.5\r\n- Cloud provider or hardware configuration: vSphere\r\n- OS (e.g. from /etc/os-release): ubuntu 14.04.5 LTS\r\n- Kernel (e.g. `uname -a`): 4.4.0-116-generic\r\n- Install tools: CFCR/PKS\r\n- Others:\r\n/sig vmware",
  "closed_at": "2018-04-23T22:45:14Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 0,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62435/comments",
  "created_at": "2018-04-11T23:41:03Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62435/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/62435",
  "id": 313525388,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": "Issues or PRs related to vmware provider",
      "id": 874113778,
      "name": "area/provider/vmware",
      "node_id": "MDU6TGFiZWw4NzQxMTM3Nzg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/provider/vmware"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62435/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzMTM1MjUzODg=",
  "number": 62435,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Disks fail to detach when upgrading from 1.9.2 to 1.9.5",
  "updated_at": "2018-04-23T22:45:14Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62435",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/5715687?v=4",
    "events_url": "https://api.github.com/users/altonf4/events{/privacy}",
    "followers_url": "https://api.github.com/users/altonf4/followers",
    "following_url": "https://api.github.com/users/altonf4/following{/other_user}",
    "gists_url": "https://api.github.com/users/altonf4/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/altonf4",
    "id": 5715687,
    "login": "altonf4",
    "node_id": "MDQ6VXNlcjU3MTU2ODc=",
    "organizations_url": "https://api.github.com/users/altonf4/orgs",
    "received_events_url": "https://api.github.com/users/altonf4/received_events",
    "repos_url": "https://api.github.com/users/altonf4/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/altonf4/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/altonf4/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/altonf4"
  }
}