{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "<!-- This form is for bug reports and feature requests ONLY! \r\n\r\nIf you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).\r\n-->\r\n\r\n**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n\r\n/kind bug\r\n\r\n\r\n**What happened**:\r\n\r\nSee,\r\n\r\n```\r\nfunc tryIPVSProxy(iptver iptables.IPTablesVersioner, kcompat iptables.KernelCompatTester) string {\r\n\t// guaranteed false on error, error only necessary for debugging\r\n\t// IPVS Proxier relies on iptables\r\n\tuseIPVSProxy, err := ipvs.CanUseIPVSProxier()\r\n\tif err != nil {\r\n\t\tutilruntime.HandleError(fmt.Errorf(\"can't determine whether to use ipvs proxy, using userspace proxier: %v\", err))\r\n\t\treturn proxyModeUserspace\r\n\t}\r\n\tif useIPVSProxy {\r\n\t\treturn proxyModeIPVS\r\n\t}\r\n\r\n\t// TODO: Check ipvs version\r\n\r\n\t// Try to fallback to iptables before falling back to userspace\r\n\tglog.V(1).Infof(\"Can't use ipvs proxier, trying iptables proxier\")\r\n\treturn tryIPTablesProxy(iptver, kcompat)\r\n}\r\n```\r\n\r\nKube-proxy will fallback to userspace mode when unable to load kernel modules. That's not intended.\r\n\r\n**What you expected to happen**:\r\n\r\nkube-proxy should fall back to iptables firstly when unable to load kernel modules\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`):\r\n- Cloud provider or hardware configuration**:\r\n- OS (e.g. from /etc/os-release):\r\n- Kernel (e.g. `uname -a`):\r\n- Install tools:\r\n- Others:\r\n\r\n/sig network\r\n",
  "closed_at": "2017-11-03T06:02:11Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 0,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/54121/comments",
  "created_at": "2017-10-18T06:34:49Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/54121/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/54121",
  "id": 266374132,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Network.",
      "id": 116712108,
      "name": "sig/network",
      "node_id": "MDU6TGFiZWwxMTY3MTIxMDg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/network"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/54121/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUyNjYzNzQxMzI=",
  "number": 54121,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "kube-proxy should fall back to iptables firstly when unable to load kernel modules",
  "updated_at": "2017-11-03T06:02:11Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/54121",
  "user": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/4953962?v=4",
    "events_url": "https://api.github.com/users/m1093782566/events{/privacy}",
    "followers_url": "https://api.github.com/users/m1093782566/followers",
    "following_url": "https://api.github.com/users/m1093782566/following{/other_user}",
    "gists_url": "https://api.github.com/users/m1093782566/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/m1093782566",
    "id": 4953962,
    "login": "m1093782566",
    "node_id": "MDQ6VXNlcjQ5NTM5NjI=",
    "organizations_url": "https://api.github.com/users/m1093782566/orgs",
    "received_events_url": "https://api.github.com/users/m1093782566/received_events",
    "repos_url": "https://api.github.com/users/m1093782566/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/m1093782566/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/m1093782566/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/m1093782566"
  }
}