{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "<!-- **Are you in the right place?**\r\n1. For issues or feature requests, please create an issue in this repository.\r\n2. For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://Rook-io.slack.com).\r\n3. Did you already search the existing open issues for anything similar? -->\r\n\r\n**Is this a bug report or feature request?**\r\n* Bug Report\r\n\r\n**Deviation from expected behavior:**\r\nOn March 1st, we started seeing intermittent failures in the master builds in the test `TestFileStorageMountUser_SmokeTest`. \r\n\r\nThe issue has been seen in builds 977, 978, 979, and [984](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/984/pipeline/41/) thus far. Builds 980-983 did not hit this issue. Perhaps coincidentally, each failure always happened on K8s 1.11, but in the last build it also hit on K8s 1.12.\r\n\r\n```\r\n--- FAIL: TestSmokeSuite (462.26s)\r\n    --- PASS: TestSmokeSuite/TestBlockCSI_SmokeTest (0.01s)\r\n    --- PASS: TestSmokeSuite/TestBlockStorage_SmokeTest (116.38s)\r\n    --- FAIL: TestSmokeSuite/TestFileStorageMountUser_SmokeTest (16.87s)\r\n        require.go:765: \r\n            \tError Trace:\tfilesystem_mountuser_test.go:65\r\n            \t            \t\t\t\tfilesystem_mountuser_test.go:46\r\n            \t            \t\t\t\tsmoke_test.go:94\r\n            \tError:      \tExpected nil, but got: &errors.errorString{s:\"kubectl exec command bash failed on pod rook-ceph-tools in namespace smoke-ns: Failed to run: kubectl [exec -n smoke-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs-mountuser,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook] : Failed to complete 'kubectl': exit status 2. . output: mount error 2 = No such file or directory\\ncommand terminated with exit code 2\"}\r\n            \tTest:       \tTestSmokeSuite/TestFileStorageMountUser_SmokeTest\r\n```\r\n\r\n@BlaineEXE Could you take a look? The last PR merged around this time was #2702, though it's not clearly related to that either.\r\n\r\n**Expected behavior:**\r\nNo intermittent CI issues\r\n",
  "closed_at": "2019-03-14T16:37:36Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1048514?v=4",
    "events_url": "https://api.github.com/users/travisn/events{/privacy}",
    "followers_url": "https://api.github.com/users/travisn/followers",
    "following_url": "https://api.github.com/users/travisn/following{/other_user}",
    "gists_url": "https://api.github.com/users/travisn/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/travisn",
    "id": 1048514,
    "login": "travisn",
    "node_id": "MDQ6VXNlcjEwNDg1MTQ=",
    "organizations_url": "https://api.github.com/users/travisn/orgs",
    "received_events_url": "https://api.github.com/users/travisn/received_events",
    "repos_url": "https://api.github.com/users/travisn/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/travisn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/travisn/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/travisn"
  },
  "comments": 1,
  "comments_url": "https://api.github.com/repos/rook/rook/issues/2760/comments",
  "created_at": "2019-03-05T00:43:15Z",
  "events_url": "https://api.github.com/repos/rook/rook/issues/2760/events",
  "html_url": "https://github.com/rook/rook/issues/2760",
  "id": 417060341,
  "labels": [
    {
      "color": "ef5c55",
      "default": false,
      "description": "main ceph tag",
      "id": 479456042,
      "name": "ceph",
      "node_id": "MDU6TGFiZWw0Nzk0NTYwNDI=",
      "url": "https://api.github.com/repos/rook/rook/labels/ceph"
    },
    {
      "color": "5522ee",
      "default": false,
      "description": "",
      "id": 626631231,
      "name": "reliability",
      "node_id": "MDU6TGFiZWw2MjY2MzEyMzE=",
      "url": "https://api.github.com/repos/rook/rook/labels/reliability"
    },
    {
      "color": "5319e7",
      "default": false,
      "description": "unit or integration testing",
      "id": 607329642,
      "name": "test",
      "node_id": "MDU6TGFiZWw2MDczMjk2NDI=",
      "url": "https://api.github.com/repos/rook/rook/labels/test"
    }
  ],
  "labels_url": "https://api.github.com/repos/rook/rook/issues/2760/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0MTcwNjAzNDE=",
  "number": 2760,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/rook/rook",
  "state": "closed",
  "title": "Intermittent failure with fs mount in TestFileStorageMountUser_SmokeTest",
  "updated_at": "2019-03-14T16:37:36Z",
  "url": "https://api.github.com/repos/rook/rook/issues/2760",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1048514?v=4",
    "events_url": "https://api.github.com/users/travisn/events{/privacy}",
    "followers_url": "https://api.github.com/users/travisn/followers",
    "following_url": "https://api.github.com/users/travisn/following{/other_user}",
    "gists_url": "https://api.github.com/users/travisn/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/travisn",
    "id": 1048514,
    "login": "travisn",
    "node_id": "MDQ6VXNlcjEwNDg1MTQ=",
    "organizations_url": "https://api.github.com/users/travisn/orgs",
    "received_events_url": "https://api.github.com/users/travisn/received_events",
    "repos_url": "https://api.github.com/users/travisn/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/travisn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/travisn/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/travisn"
  }
}