{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "**Environment**:\r\n* OS: RHEL 7.7\r\n* Cloud provider or hardware configuration: Openshift\r\n* Rook version: v1.3.1\r\n* Storage backend version: ceph v15.2.0\r\n* Kubernetes version : v1.11+\r\n* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):Openshift\r\n\r\nWhen i am trying to use metadatadevice (which was working in rook 1.2.7 with ceph v14.2.8) it is the osd prepare pod is failing and giving the following error.\r\n```\r\n2020-04-20 10:44:10.880645 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/vdb /dev/vdc --db-devices /dev/vdc --report\r\n2020-04-20 10:44:32.018194 D | exec: Traceback (most recent call last):\r\n2020-04-20 10:44:32.018275 D | exec:   File \"/usr/sbin/ceph-volume\", line 9, in <module>\r\n2020-04-20 10:44:32.018320 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()\r\n2020-04-20 10:44:32.018340 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 39, in __init__\r\n2020-04-20 10:44:32.018355 D | exec:     self.main(self.argv)\r\n2020-04-20 10:44:32.018375 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 59, in newfunc\r\n2020-04-20 10:44:32.018385 D | exec:     return f(*a, **kw)\r\n2020-04-20 10:44:32.018400 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 150, in main\r\n2020-04-20 10:44:32.018406 D | exec:     terminal.dispatch(self.mapper, subcommand_args)\r\n2020-04-20 10:44:32.018411 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\r\n2020-04-20 10:44:32.018417 D | exec:     instance.main()\r\n2020-04-20 10:44:32.018422 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py\", line 42, in main\r\n2020-04-20 10:44:32.018428 D | exec:     terminal.dispatch(self.mapper, self.argv)\r\n2020-04-20 10:44:32.018434 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\r\n2020-04-20 10:44:32.018458 D | exec:     instance.main()\r\n2020-04-20 10:44:32.018490 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 16, in is_root\r\n2020-04-20 10:44:32.018499 D | exec:     return func(*a, **kw)\r\n2020-04-20 10:44:32.018510 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 318, in main\r\n2020-04-20 10:44:32.018532 D | exec:     self._get_explicit_strategy()\r\n2020-04-20 10:44:32.018577 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 329, in _get_explicit_strategy\r\n2020-04-20 10:44:32.018599 D | exec:     self._ensure_disjoint_device_lists()\r\n2020-04-20 10:44:32.018625 D | exec:   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 380, in _ensure_disjoint_device_lists\r\n2020-04-20 10:44:32.018636 D | exec:     raise Exception('Device lists are not disjoint')\r\n2020-04-20 10:44:32.018661 D | exec: Exception: Device lists are not disjoint\r\nfailed to configure devices: failed to initialize devices: failed ceph-volume report: exit status 1\r\n```",
  "closed_at": "2020-04-23T21:03:16Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1048514?v=4",
    "events_url": "https://api.github.com/users/travisn/events{/privacy}",
    "followers_url": "https://api.github.com/users/travisn/followers",
    "following_url": "https://api.github.com/users/travisn/following{/other_user}",
    "gists_url": "https://api.github.com/users/travisn/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/travisn",
    "id": 1048514,
    "login": "travisn",
    "node_id": "MDQ6VXNlcjEwNDg1MTQ=",
    "organizations_url": "https://api.github.com/users/travisn/orgs",
    "received_events_url": "https://api.github.com/users/travisn/received_events",
    "repos_url": "https://api.github.com/users/travisn/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/travisn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/travisn/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/travisn"
  },
  "comments": 6,
  "comments_url": "https://api.github.com/repos/rook/rook/issues/5300/comments",
  "created_at": "2020-04-21T09:16:07Z",
  "events_url": "https://api.github.com/repos/rook/rook/issues/5300/events",
  "html_url": "https://github.com/rook/rook/issues/5300",
  "id": 603842006,
  "labels": [
    {
      "color": "ee0000",
      "default": true,
      "description": "",
      "id": 405241115,
      "name": "bug",
      "node_id": "MDU6TGFiZWw0MDUyNDExMTU=",
      "url": "https://api.github.com/repos/rook/rook/labels/bug"
    },
    {
      "color": "ef5c55",
      "default": false,
      "description": "main ceph tag",
      "id": 479456042,
      "name": "ceph",
      "node_id": "MDU6TGFiZWw0Nzk0NTYwNDI=",
      "url": "https://api.github.com/repos/rook/rook/labels/ceph"
    }
  ],
  "labels_url": "https://api.github.com/repos/rook/rook/issues/5300/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU2MDM4NDIwMDY=",
  "number": 5300,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/rook/rook",
  "state": "closed",
  "title": "CephCluster CR is correct but the metadata device is applied incorrectly",
  "updated_at": "2020-04-23T21:03:16Z",
  "url": "https://api.github.com/repos/rook/rook/issues/5300",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/18174818?v=4",
    "events_url": "https://api.github.com/users/shikhar7/events{/privacy}",
    "followers_url": "https://api.github.com/users/shikhar7/followers",
    "following_url": "https://api.github.com/users/shikhar7/following{/other_user}",
    "gists_url": "https://api.github.com/users/shikhar7/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/shikhar7",
    "id": 18174818,
    "login": "shikhar7",
    "node_id": "MDQ6VXNlcjE4MTc0ODE4",
    "organizations_url": "https://api.github.com/users/shikhar7/orgs",
    "received_events_url": "https://api.github.com/users/shikhar7/received_events",
    "repos_url": "https://api.github.com/users/shikhar7/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/shikhar7/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shikhar7/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/shikhar7"
  }
}